import { REGION_COUNTRY_OPTIONS } from "@/lib/region-country-options";

export type CanonicalFilterRegionKey =
  | "global"
  | "africa-east-and-southern"
  | "africa-north-and-middle-east"
  | "africa-west-and-central"
  | "america-latin"
  | "america-north-and-caribbean"
  | "asia-central"
  | "asia-northeast"
  | "asia-south"
  | "asia-southeast"
  | "australia-and-pacific"
  | "europe-eastern-and-eurasia"
  | "europe-western";

export type CanonicalFilterRegionDefinition = {
  key: CanonicalFilterRegionKey;
  name: string;
  description: string;
  sortOrder: number;
  countries: string[];
};

const LEGACY_REGION_NAME_ALIASES = new Map<string, string>([
  ["globe", "Global"],
  ["south asia", "Asia, South"],
  ["south east asia", "Asia, Southeast"],
]);

export function normalizeCompatibleRegionName(name: string) {
  const trimmedName = name.trim();
  const alias = LEGACY_REGION_NAME_ALIASES.get(trimmedName.toLowerCase());
  return alias ?? trimmedName;
}

export const CANONICAL_FILTER_REGION_DEFINITIONS = [
  {
    key: "global",
    name: "Global",
    description: "All countries",
    sortOrder: 1,
    countries: [...REGION_COUNTRY_OPTIONS],
  },
  {
    key: "africa-east-and-southern",
    name: "Africa, East and Southern",
    description: "",
    sortOrder: 2,
    countries: [
      "Angola",
      "Botswana",
      "Burundi",
      "Comoros",
      "Djibouti",
      "Eritrea",
      "Eswatini",
      "Ethiopia",
      "Kenya",
      "Lesotho",
      "Madagascar",
      "Malawi",
      "Mauritius",
      "Mayotte",
      "Mozambique",
      "Namibia",
      "Reunion",
      "Rwanda",
      "Saint Helena, Ascension and Tristan da Cunha",
      "Seychelles",
      "Somalia",
      "South Africa",
      "South Sudan",
      "Sudan",
      "Tanzania, the United Republic of",
      "Uganda",
      "Zambia",
      "Zimbabwe",
    ],
  },
  {
    key: "africa-north-and-middle-east",
    name: "Africa, North and Middle East",
    description: "",
    sortOrder: 3,
    countries: [
      "Algeria",
      "Bahrain",
      "Egypt",
      "Iraq",
      "Israel",
      "Jordan",
      "Kuwait",
      "Lebanon",
      "Libya",
      "Morocco",
      "Oman",
      "Qatar",
      "Saudi Arabia",
      "Syria",
      "Tunisia",
      "United Arab Emirates",
      "West Bank",
      "Gaza Strip",
      "Palestine",
      "Western Sahara",
      "Yemen",
    ],
  },
  {
    key: "africa-west-and-central",
    name: "Africa, West and Central",
    description: "",
    sortOrder: 4,
    countries: [
      "Benin",
      "Burkina Faso",
      "Cameroon",
      "Cabo Verde",
      "Central African Republic",
      "Chad",
      "Democratic Republic of the Congo",
      "Congo",
      "Ivory Coast",
      "Equatorial Guinea",
      "Gabon",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Liberia",
      "Mali",
      "Mauritania",
      "Niger",
      "Nigeria",
      "Sao Tome and Principe",
      "Senegal",
      "Sierra Leone",
      "Togo",
    ],
  },
  {
    key: "america-latin",
    name: "America, Latin",
    description: "",
    sortOrder: 5,
    countries: [
      "Argentina",
      "Belize",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Costa Rica",
      "Ecuador",
      "El Salvador",
      "Falkland Islands",
      "French Guiana",
      "Guatemala",
      "Guyana",
      "Honduras",
      "Mexico",
      "Nicaragua",
      "Panama",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela",
    ],
  },
  {
    key: "america-north-and-caribbean",
    name: "America, North and Caribbean",
    description: "",
    sortOrder: 6,
    countries: [
      "Anguilla",
      "Antigua and Barbuda",
      "Aruba",
      "Bahamas",
      "Barbados",
      "Bermuda",
      "the British Virgin Islands",
      "Canada",
      "Cayman Islands",
      "Cuba",
      "Curacao",
      "Dominica",
      "Dominican Republic",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Haiti",
      "Jamaica",
      "Martinique",
      "Montserrat",
      "Puerto Rico",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Pierre and Miquelon",
      "Saint Maarten (Dutch)",
      "Saint Vincent and the Grenadines",
      "Trinidad and Tobago",
      "Turks and Caicos Islands",
      "United States of America",
      "Virgin Islands",
    ],
  },
  {
    key: "asia-central",
    name: "Asia, Central",
    description: "",
    sortOrder: 7,
    countries: [
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Iran",
      "Kazakhstan",
      "Kyrgyzstan",
      "Tajikistan",
      "Turkey",
      "Turkmenistan",
      "Uzbekistan",
    ],
  },
  {
    key: "asia-northeast",
    name: "Asia, Northeast",
    description: "",
    sortOrder: 8,
    countries: [
      "China",
      "Hong Kong",
      "Macao",
      "Japan",
      "North Korea",
      "South Korea",
      "Mongolia",
      "Taiwan",
    ],
  },
  {
    key: "asia-south",
    name: "Asia, South",
    description: "",
    sortOrder: 9,
    countries: [
      "Bangladesh",
      "Bhutan",
      "British Indian Ocean Territory",
      "India",
      "Maldives",
      "Nepal",
      "Pakistan",
      "Sri Lanka",
    ],
  },
  {
    key: "asia-southeast",
    name: "Asia, Southeast",
    description: "",
    sortOrder: 10,
    countries: [
      "Brunei Darussalam",
      "Cambodia",
      "Indonesia",
      "Lao",
      "Malaysia",
      "Myanmar",
      "Philippines",
      "Singapore",
      "Thailand",
      "Timor-Leste",
      "Vietnam",
    ],
  },
  {
    key: "australia-and-pacific",
    name: "Australia and Pacific",
    description: "",
    sortOrder: 11,
    countries: [
      "American Samoa",
      "Australia",
      "Christmas Island",
      "Cocos Islands",
      "Cook Islands",
      "Fiji",
      "French Polynesia",
      "Guam",
      "Kiribati",
      "Marshall Islands",
      "Micronesia",
      "Nauru",
      "New Caledonia",
      "New Zealand",
      "Niue",
      "Norfolk Island",
      "Northern Mariana Islands",
      "Palau",
      "Papua New Guinea",
      "Pitcairn",
      "Samoa",
      "Solomon Islands",
      "Tokelau",
      "Tonga",
      "Tuvalu",
      "Vanuatu",
      "Wallis and Futuna",
    ],
  },
  {
    key: "europe-eastern-and-eurasia",
    name: "Europe, Eastern and Eurasia",
    description: "",
    sortOrder: 12,
    countries: [
      "Albania",
      "Belarus",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Czechia",
      "Estonia",
      "Georgia",
      "Greece",
      "Hungary",
      "Kosovo",
      "Latvia",
      "Lithuania",
      "Moldova",
      "Montenegro",
      "North Macedonia",
      "Poland",
      "Romania",
      "Russia",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Ukraine",
    ],
  },
  {
    key: "europe-western",
    name: "Europe, Western",
    description: "",
    sortOrder: 13,
    countries: [
      "Andorra",
      "Austria",
      "Belgium",
      "Cyprus",
      "Denmark",
      "Faroe Islands",
      "Finland",
      "France",
      "Germany",
      "Gibraltar",
      "Iceland",
      "Ireland",
      "Isle of Man",
      "Italy",
      "Liechtenstein",
      "Luxembourg",
      "Malta",
      "Monaco",
      "Netherlands",
      "Norway",
      "Portugal",
      "San Marino",
      "Spain",
      "Svalbard and Jan Mayen",
      "Sweden",
      "Switzerland",
      "United Kingdom of Great Britain and Northern Ireland",
      "Holy See",
    ],
  },
] as const satisfies readonly CanonicalFilterRegionDefinition[];
