/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=infra/cloudflare/qwen-edge-gateway/wrangler.jsonc --include-runtime=false --env-interface=QwenEdgeEnv infra/cloudflare/qwen-edge-gateway/worker-configuration.d.ts` (hash: 3e93fbe932c34526b52e1ab1f5dbf126)
interface __BaseEnv_QwenEdgeEnv {
	PRIVATE_QWEN: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_QwenEdgeEnv {}
}
interface QwenEdgeEnv extends __BaseEnv_QwenEdgeEnv {}
