import type { SmokeRouteSpec } from "./types";

export const smokeRouteSpecs: SmokeRouteSpec[] = [
  {
    id: "home-sign-in-anonymous",
    role: "anonymous",
    pageFile: "src/app/page.tsx",
    path: "/",
    pageId: "home-sign-in",
  },
  {
    id: "sign-up-anonymous",
    role: "anonymous",
    pageFile: "src/app/sign-up/page.tsx",
    path: "/sign-up",
    pageId: "sign-up",
    journeys: [
      "allowlisted user can sign up",
      "blocked user cannot sign up",
    ],
  },
  {
    id: "forgot-password-anonymous",
    role: "anonymous",
    pageFile: "src/app/forgot-password/page.tsx",
    path: "/forgot-password",
    pageId: "forgot-password",
    journeys: ["forgot-password request succeeds"],
  },
  {
    id: "reset-password-anonymous",
    role: "anonymous",
    pageFile: "src/app/reset-password/page.tsx",
    path: "/reset-password",
    pageId: "reset-password",
    journeys: [
      "recovery link lands on reset-password",
      "password reset completes",
    ],
  },
  {
    id: "sign-in-redirect-anonymous",
    role: "anonymous",
    pageFile: "src/app/sign-in/page.tsx",
    path: "/sign-in",
    redirectTo: "/",
  },
  {
    id: "smoke-components-anonymous",
    role: "anonymous",
    pageFile: "src/app/%5F_smoke/components/page.tsx",
    path: "/__smoke/components",
    pageId: "smoke-components",
    assertFixtureCoverage: true,
  },
  {
    id: "dashboard-viewer",
    role: "viewer",
    pageFile: "src/app/dashboard/page.tsx",
    path: "/dashboard",
    pageId: "dashboard",
  },
  {
    id: "dashboard-admin",
    role: "admin",
    pageFile: "src/app/dashboard/page.tsx",
    path: "/dashboard",
    pageId: "dashboard",
    journeys: ["admin can edit dataset details"],
  },
  {
    id: "data-lake-viewer",
    role: "viewer",
    pageFile: "src/app/dashboard/data-lake/page.tsx",
    path: "/dashboard/data-lake",
    pageId: "data-lake",
  },
  {
    id: "data-lake-admin",
    role: "admin",
    pageFile: "src/app/dashboard/data-lake/page.tsx",
    path: "/dashboard/data-lake",
    pageId: "data-lake",
  },
  {
    id: "datasets-index-viewer",
    role: "viewer",
    pageFile: "src/app/dashboard/datasets/page.tsx",
    path: "/dashboard/datasets",
    redirectTo: "/dashboard/datasets/{{primaryDatasetId}}?source=default_redirect",
  },
  {
    id: "datasets-index-admin",
    role: "admin",
    pageFile: "src/app/dashboard/datasets/page.tsx",
    path: "/dashboard/datasets",
    redirectTo: "/dashboard/datasets/{{primaryDatasetId}}?source=default_redirect",
  },
  {
    id: "dataset-detail-viewer",
    role: "viewer",
    pageFile: "src/app/dashboard/datasets/[datasetId]/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}",
    pageId: "dataset-detail",
    journeys: ["authenticated user can save a filtered table"],
  },
  {
    id: "dataset-detail-admin",
    role: "admin",
    pageFile: "src/app/dashboard/datasets/[datasetId]/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}",
    pageId: "dataset-detail",
  },
  {
    id: "dataset-edit-viewer-redirect",
    role: "viewer",
    pageFile: "src/app/dashboard/datasets/[datasetId]/edit/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}/edit",
    redirectTo: "/dashboard/datasets/{{primaryDatasetId}}",
  },
  {
    id: "dataset-edit-admin",
    role: "admin",
    pageFile: "src/app/dashboard/datasets/[datasetId]/edit/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}/edit",
    pageId: "dataset-edit",
  },
  {
    id: "field-definitions-viewer",
    role: "viewer",
    pageFile: "src/app/dashboard/field-definitions/page.tsx",
    path: "/dashboard/field-definitions",
    pageId: "field-definitions",
  },
  {
    id: "field-definitions-admin",
    role: "admin",
    pageFile: "src/app/dashboard/field-definitions/page.tsx",
    path: "/dashboard/field-definitions",
    pageId: "field-definitions",
    journeys: ["admin can edit a field definition"],
  },
  {
    id: "field-sources-viewer-redirect",
    role: "viewer",
    pageFile: "src/app/dashboard/field-sources/page.tsx",
    path: "/dashboard/field-sources",
    redirectTo: "/dashboard",
  },
  {
    id: "field-sources-admin",
    role: "admin",
    pageFile: "src/app/dashboard/field-sources/page.tsx",
    path: "/dashboard/field-sources",
    pageId: "field-sources",
    journeys: ["admin can create a source column and update a field source value"],
  },
  {
    id: "profile-viewer",
    role: "viewer",
    pageFile: "src/app/dashboard/profile/page.tsx",
    path: "/dashboard/profile",
    pageId: "profile",
    journeys: [
      "signed-in user can sign out",
      "disabled user cannot sign back in",
    ],
  },
  {
    id: "profile-admin",
    role: "admin",
    pageFile: "src/app/dashboard/profile/page.tsx",
    path: "/dashboard/profile",
    pageId: "profile",
  },
  {
    id: "user-management-viewer-redirect",
    role: "viewer",
    pageFile: "src/app/dashboard/user-management/page.tsx",
    path: "/dashboard/user-management",
    redirectTo: "/dashboard",
  },
  {
    id: "user-management-admin",
    role: "admin",
    pageFile: "src/app/dashboard/user-management/page.tsx",
    path: "/dashboard/user-management",
    pageId: "user-management",
  },
  {
    id: "analytics-viewer-redirect",
    role: "viewer",
    pageFile: "src/app/dashboard/analytics/page.tsx",
    path: "/dashboard/analytics",
    redirectTo: "/dashboard",
  },
  {
    id: "analytics-admin",
    role: "admin",
    pageFile: "src/app/dashboard/analytics/page.tsx",
    path: "/dashboard/analytics",
    pageId: "analytics",
  },
  {
    id: "upload-viewer-redirect",
    role: "viewer",
    pageFile: "src/app/dashboard/upload/page.tsx",
    path: "/dashboard/upload",
    redirectTo: "/dashboard",
  },
  {
    id: "upload-admin",
    role: "admin",
    pageFile: "src/app/dashboard/upload/page.tsx",
    path: "/dashboard/upload",
    pageId: "upload",
    journeys: ["admin can replace a dataset through the real upload flow"],
  },
];
