import type { SmokeRouteSpec } from "./types";

export const smokeRouteSpecs: SmokeRouteSpec[] = [
  {
    id: "home-sign-in-anonymous",
    role: "anonymous",
    pageFile: "src/app/page.tsx",
    path: "/",
    pageId: "home-sign-in",
  },
  {
    id: "sign-up-anonymous",
    role: "anonymous",
    pageFile: "src/app/sign-up/page.tsx",
    path: "/sign-up",
    pageId: "sign-up",
    journeys: [
      "allowlisted user can sign up",
      "blocked user cannot sign up",
    ],
  },
  {
    id: "forgot-password-anonymous",
    role: "anonymous",
    pageFile: "src/app/forgot-password/page.tsx",
    path: "/forgot-password",
    pageId: "forgot-password",
    journeys: ["forgot-password request succeeds"],
  },
  {
    id: "reset-password-anonymous",
    role: "anonymous",
    pageFile: "src/app/reset-password/page.tsx",
    path: "/reset-password",
    pageId: "reset-password",
    journeys: [
      "recovery link lands on reset-password",
      "password reset completes",
    ],
  },
  {
    id: "sign-in-redirect-anonymous",
    role: "anonymous",
    pageFile: "src/app/sign-in/page.tsx",
    path: "/sign-in",
    redirectTo: "/",
  },
  {
    id: "smoke-components-anonymous",
    role: "anonymous",
    pageFile: "src/app/%5F_smoke/components/page.tsx",
    path: "/__smoke/components",
    pageId: "smoke-components",
    assertFixtureCoverage: true,
  },
  {
    id: "dashboard-pro",
    role: "pro",
    pageFile: "src/app/dashboard/page.tsx",
    path: "/dashboard",
    pageId: "dashboard",
  },
  {
    id: "dashboard-basic",
    role: "basic",
    pageFile: "src/app/dashboard/page.tsx",
    path: "/dashboard",
    pageId: "dashboard",
  },
  {
    id: "dashboard-admin",
    role: "admin",
    pageFile: "src/app/dashboard/page.tsx",
    path: "/dashboard",
    pageId: "dashboard",
    journeys: ["admin can edit dataset details"],
  },
  {
    id: "datasets-index-pro",
    role: "pro",
    pageFile: "src/app/dashboard/datasets/page.tsx",
    path: "/dashboard/datasets",
    redirectTo: "/dashboard/datasets/{{primaryDatasetId}}?source=default_redirect",
  },
  {
    id: "datasets-index-basic",
    role: "basic",
    pageFile: "src/app/dashboard/datasets/page.tsx",
    path: "/dashboard/datasets",
    redirectTo: "/dashboard/datasets/{{primaryDatasetId}}?source=default_redirect",
  },
  {
    id: "datasets-index-admin",
    role: "admin",
    pageFile: "src/app/dashboard/datasets/page.tsx",
    path: "/dashboard/datasets",
    redirectTo: "/dashboard/datasets/{{primaryDatasetId}}?source=default_redirect",
  },
  {
    id: "dataset-detail-pro",
    role: "pro",
    pageFile: "src/app/dashboard/datasets/[datasetId]/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}",
    pageId: "dataset-detail",
    journeys: ["authenticated user can save a filtered table"],
  },
  {
    id: "dataset-detail-basic",
    role: "basic",
    pageFile: "src/app/dashboard/datasets/[datasetId]/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}",
    pageId: "dataset-detail",
    journeys: ["basic user can filter and download without saving"],
  },
  {
    id: "dataset-detail-admin",
    role: "admin",
    pageFile: "src/app/dashboard/datasets/[datasetId]/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}",
    pageId: "dataset-detail",
  },
  {
    id: "dataset-edit-pro-redirect",
    role: "pro",
    pageFile: "src/app/dashboard/datasets/[datasetId]/edit/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}/edit",
    redirectTo: "/dashboard/datasets/{{primaryDatasetId}}",
  },
  {
    id: "dataset-edit-basic-redirect",
    role: "basic",
    pageFile: "src/app/dashboard/datasets/[datasetId]/edit/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}/edit",
    redirectTo: "/dashboard/datasets/{{primaryDatasetId}}",
  },
  {
    id: "dataset-edit-admin",
    role: "admin",
    pageFile: "src/app/dashboard/datasets/[datasetId]/edit/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}/edit",
    pageId: "dataset-edit",
  },
  {
    id: "field-definitions-pro",
    role: "pro",
    pageFile: "src/app/dashboard/field-definitions/page.tsx",
    path: "/dashboard/field-definitions",
    pageId: "field-definitions",
  },
  {
    id: "field-definitions-basic",
    role: "basic",
    pageFile: "src/app/dashboard/field-definitions/page.tsx",
    path: "/dashboard/field-definitions",
    pageId: "field-definitions",
  },
  {
    id: "field-definitions-admin",
    role: "admin",
    pageFile: "src/app/dashboard/field-definitions/page.tsx",
    path: "/dashboard/field-definitions",
    pageId: "field-definitions",
    journeys: ["admin can edit a field definition"],
  },
  {
    id: "field-sources-pro-redirect",
    role: "pro",
    pageFile: "src/app/dashboard/field-sources/page.tsx",
    path: "/dashboard/field-sources",
    redirectTo: "/dashboard",
  },
  {
    id: "field-sources-basic-redirect",
    role: "basic",
    pageFile: "src/app/dashboard/field-sources/page.tsx",
    path: "/dashboard/field-sources",
    redirectTo: "/dashboard",
  },
  {
    id: "field-sources-admin",
    role: "admin",
    pageFile: "src/app/dashboard/field-sources/page.tsx",
    path: "/dashboard/field-sources",
    pageId: "field-sources",
    journeys: ["admin can review field source mappings"],
  },
  {
    id: "iso-country-codes-pro",
    role: "pro",
    pageFile: "src/app/dashboard/country-codes/page.tsx",
    path: "/dashboard/country-codes",
    pageId: "iso-country-codes",
  },
  {
    id: "iso-country-codes-basic",
    role: "basic",
    pageFile: "src/app/dashboard/country-codes/page.tsx",
    path: "/dashboard/country-codes",
    pageId: "iso-country-codes",
  },
  {
    id: "iso-country-codes-admin",
    role: "admin",
    pageFile: "src/app/dashboard/country-codes/page.tsx",
    path: "/dashboard/country-codes",
    pageId: "iso-country-codes",
  },
  {
    id: "profile-pro",
    role: "pro",
    pageFile: "src/app/dashboard/profile/page.tsx",
    path: "/dashboard/profile",
    pageId: "profile",
    journeys: [
      "signed-in user can sign out",
      "disabled user cannot sign back in",
    ],
  },
  {
    id: "profile-basic",
    role: "basic",
    pageFile: "src/app/dashboard/profile/page.tsx",
    path: "/dashboard/profile",
    pageId: "profile",
    journeys: ["basic profile is read-only"],
  },
  {
    id: "profile-admin",
    role: "admin",
    pageFile: "src/app/dashboard/profile/page.tsx",
    path: "/dashboard/profile",
    pageId: "profile",
  },
  {
    id: "user-management-pro-redirect",
    role: "pro",
    pageFile: "src/app/dashboard/user-management/page.tsx",
    path: "/dashboard/user-management",
    redirectTo: "/dashboard",
  },
  {
    id: "user-management-basic-redirect",
    role: "basic",
    pageFile: "src/app/dashboard/user-management/page.tsx",
    path: "/dashboard/user-management",
    redirectTo: "/dashboard",
  },
  {
    id: "user-management-admin",
    role: "admin",
    pageFile: "src/app/dashboard/user-management/page.tsx",
    path: "/dashboard/user-management",
    pageId: "user-management",
  },
  {
    id: "analytics-pro-redirect",
    role: "pro",
    pageFile: "src/app/dashboard/analytics/page.tsx",
    path: "/dashboard/analytics",
    redirectTo: "/dashboard",
  },
  {
    id: "analytics-basic-redirect",
    role: "basic",
    pageFile: "src/app/dashboard/analytics/page.tsx",
    path: "/dashboard/analytics",
    redirectTo: "/dashboard",
  },
  {
    id: "analytics-admin",
    role: "admin",
    pageFile: "src/app/dashboard/analytics/page.tsx",
    path: "/dashboard/analytics",
    pageId: "analytics",
  },
  {
    id: "api-connections-pro-redirect",
    role: "pro",
    pageFile: "src/app/dashboard/api-connections/page.tsx",
    path: "/dashboard/api-connections",
    redirectTo: "/dashboard",
  },
  {
    id: "api-connections-basic-redirect",
    role: "basic",
    pageFile: "src/app/dashboard/api-connections/page.tsx",
    path: "/dashboard/api-connections",
    redirectTo: "/dashboard",
  },
  {
    id: "api-connections-admin",
    role: "admin",
    pageFile: "src/app/dashboard/api-connections/page.tsx",
    path: "/dashboard/api-connections",
    pageId: "api-connections",
  },
  {
    id: "api-connection-detail-pro-redirect",
    role: "pro",
    pageFile: "src/app/dashboard/api-connections/[connectionId]/page.tsx",
    path: "/dashboard/api-connections/6f9f6ef2-1188-4f71-9c24-ef01debf7a01",
    redirectTo: "/dashboard",
  },
  {
    id: "api-connection-detail-basic-redirect",
    role: "basic",
    pageFile: "src/app/dashboard/api-connections/[connectionId]/page.tsx",
    path: "/dashboard/api-connections/6f9f6ef2-1188-4f71-9c24-ef01debf7a01",
    redirectTo: "/dashboard",
  },
  {
    id: "api-connection-detail-admin",
    role: "admin",
    pageFile: "src/app/dashboard/api-connections/[connectionId]/page.tsx",
    path: "/dashboard/api-connections/6f9f6ef2-1188-4f71-9c24-ef01debf7a01",
    pageId: "api-connection-detail",
  },
  {
    id: "upload-pro-redirect",
    role: "pro",
    pageFile: "src/app/dashboard/upload/page.tsx",
    path: "/dashboard/upload",
    redirectTo: "/dashboard",
  },
  {
    id: "upload-basic-redirect",
    role: "basic",
    pageFile: "src/app/dashboard/upload/page.tsx",
    path: "/dashboard/upload",
    redirectTo: "/dashboard",
  },
  {
    id: "upload-admin",
    role: "admin",
    pageFile: "src/app/dashboard/upload/page.tsx",
    path: "/dashboard/upload",
    pageId: "upload",
    journeys: ["admin can replace a dataset through the real upload flow"],
  },
];
