import type { SmokeRouteSpec } from "./types";

export const smokeRouteSpecs: SmokeRouteSpec[] = [
  {
    id: "home-sign-in-anonymous",
    role: "anonymous",
    pageFile: "src/app/page.tsx",
    path: "/",
    pageId: "home-sign-in",
  },
  {
    id: "sign-up-anonymous",
    role: "anonymous",
    pageFile: "src/app/sign-up/page.tsx",
    path: "/sign-up",
    pageId: "sign-up",
  },
  {
    id: "forgot-password-anonymous",
    role: "anonymous",
    pageFile: "src/app/forgot-password/page.tsx",
    path: "/forgot-password",
    pageId: "forgot-password",
  },
  {
    id: "reset-password-anonymous",
    role: "anonymous",
    pageFile: "src/app/reset-password/page.tsx",
    path: "/reset-password",
    pageId: "reset-password",
  },
  {
    id: "sign-in-redirect-anonymous",
    role: "anonymous",
    pageFile: "src/app/sign-in/page.tsx",
    path: "/sign-in",
    redirectTo: "/",
  },
  {
    id: "smoke-components-anonymous",
    role: "anonymous",
    pageFile: "src/app/%5F_smoke/components/page.tsx",
    path: "/__smoke/components",
    pageId: "smoke-components",
    assertFixtureCoverage: true,
  },
  {
    id: "dashboard-viewer",
    role: "viewer",
    pageFile: "src/app/dashboard/page.tsx",
    path: "/dashboard",
    pageId: "dashboard",
  },
  {
    id: "dashboard-admin",
    role: "admin",
    pageFile: "src/app/dashboard/page.tsx",
    path: "/dashboard",
    pageId: "dashboard",
    journeys: ["admin can edit dataset details"],
  },
  {
    id: "datasets-index-viewer",
    role: "viewer",
    pageFile: "src/app/dashboard/datasets/page.tsx",
    path: "/dashboard/datasets",
    redirectTo: "/dashboard/datasets/{{primaryDatasetId}}",
  },
  {
    id: "datasets-index-admin",
    role: "admin",
    pageFile: "src/app/dashboard/datasets/page.tsx",
    path: "/dashboard/datasets",
    redirectTo: "/dashboard/datasets/{{primaryDatasetId}}",
  },
  {
    id: "dataset-detail-viewer",
    role: "viewer",
    pageFile: "src/app/dashboard/datasets/[datasetId]/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}",
    pageId: "dataset-detail",
  },
  {
    id: "dataset-detail-admin",
    role: "admin",
    pageFile: "src/app/dashboard/datasets/[datasetId]/page.tsx",
    path: "/dashboard/datasets/{{primaryDatasetId}}",
    pageId: "dataset-detail",
  },
  {
    id: "field-definitions-viewer",
    role: "viewer",
    pageFile: "src/app/dashboard/field-definitions/page.tsx",
    path: "/dashboard/field-definitions",
    pageId: "field-definitions",
  },
  {
    id: "field-definitions-admin",
    role: "admin",
    pageFile: "src/app/dashboard/field-definitions/page.tsx",
    path: "/dashboard/field-definitions",
    pageId: "field-definitions",
    journeys: ["admin can edit a field definition"],
  },
  {
    id: "field-sources-viewer-redirect",
    role: "viewer",
    pageFile: "src/app/dashboard/field-sources/page.tsx",
    path: "/dashboard/field-sources",
    redirectTo: "/dashboard",
  },
  {
    id: "field-sources-admin",
    role: "admin",
    pageFile: "src/app/dashboard/field-sources/page.tsx",
    path: "/dashboard/field-sources",
    pageId: "field-sources",
    journeys: ["admin can create a source column and update a field source value"],
  },
  {
    id: "filter-settings-viewer-redirect",
    role: "viewer",
    pageFile: "src/app/dashboard/filter-settings/page.tsx",
    path: "/dashboard/filter-settings",
    redirectTo: "/dashboard",
  },
  {
    id: "filter-settings-admin",
    role: "admin",
    pageFile: "src/app/dashboard/filter-settings/page.tsx",
    path: "/dashboard/filter-settings",
    pageId: "filter-settings",
    journeys: ["admin can create and update filter settings"],
  },
  {
    id: "profile-viewer",
    role: "viewer",
    pageFile: "src/app/dashboard/profile/page.tsx",
    path: "/dashboard/profile",
    pageId: "profile",
  },
  {
    id: "profile-admin",
    role: "admin",
    pageFile: "src/app/dashboard/profile/page.tsx",
    path: "/dashboard/profile",
    pageId: "profile",
  },
  {
    id: "user-management-viewer-redirect",
    role: "viewer",
    pageFile: "src/app/dashboard/user-management/page.tsx",
    path: "/dashboard/user-management",
    redirectTo: "/dashboard",
  },
  {
    id: "user-management-admin",
    role: "admin",
    pageFile: "src/app/dashboard/user-management/page.tsx",
    path: "/dashboard/user-management",
    pageId: "user-management",
  },
  {
    id: "upload-viewer-redirect",
    role: "viewer",
    pageFile: "src/app/dashboard/upload/page.tsx",
    path: "/dashboard/upload",
    redirectTo: "/dashboard",
  },
  {
    id: "upload-admin",
    role: "admin",
    pageFile: "src/app/dashboard/upload/page.tsx",
    path: "/dashboard/upload",
    pageId: "upload",
    journeys: ["admin can replace a dataset through the real upload flow"],
  },
];
