do $$
declare
  global_region_id uuid;
begin
  select id
  into global_region_id
  from public.filter_regions
  where lower(btrim(name)) in ('global', 'globe')
  order by
    case when lower(btrim(name)) = 'global' then 0 else 1 end,
    created_at asc
  limit 1;

  if global_region_id is null then
    global_region_id := 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';

    insert into public.filter_regions (id, name, description, sort_order)
    values (global_region_id, 'Global', 'All countries', 1);
  else
    update public.filter_regions
    set
      name = 'Global',
      description = 'All countries',
      sort_order = 1,
      updated_at = now()
    where id = global_region_id;
  end if;

  delete from public.filter_regions
  where id <> global_region_id
    and lower(btrim(name)) in ('global', 'globe');

  delete from public.filter_region_countries
  where region_id = global_region_id;

  insert into public.filter_region_countries (region_id, country_name)
  select global_region_id, countries.country_name
  from (
    values
      ('Afghanistan'),
      ('Akrotiri'),
      ('Aland Islands'),
      ('Albania'),
      ('Algeria'),
      ('American Samoa'),
      ('Andorra'),
      ('Angola'),
      ('Anguilla'),
      ('Antarctica'),
      ('Antigua and Barbuda'),
      ('Argentina'),
      ('Armenia'),
      ('Aruba'),
      ('Ashmore and Cartier Islands'),
      ('Australia'),
      ('Austria'),
      ('Azerbaijan'),
      ('Bahamas'),
      ('Bahrain'),
      ('Baker Island'),
      ('Bangladesh'),
      ('Barbados'),
      ('Bassas da India'),
      ('Belarus'),
      ('Belgium'),
      ('Belize'),
      ('Benin'),
      ('Bermuda'),
      ('Bhutan'),
      ('Bolivia'),
      ('Bonaire, Sint Eustatius and Saba'),
      ('Bosnia and Herzegovina'),
      ('Botswana'),
      ('Bouvet Island'),
      ('Brazil'),
      ('British Indian Ocean Territory'),
      ('Brunei Darussalam'),
      ('Bulgaria'),
      ('Burkina Faso'),
      ('Burundi'),
      ('Cabo Verde'),
      ('Cambodia'),
      ('Cameroon'),
      ('Canada'),
      ('Cayman Islands'),
      ('Central African Republic'),
      ('Chad'),
      ('Chile'),
      ('China'),
      ('Christmas Island'),
      ('Clipperton Island'),
      ('Cocos Islands'),
      ('Colombia'),
      ('Comoros'),
      ('Congo'),
      ('Cook Islands'),
      ('Costa Rica'),
      ('Croatia'),
      ('Cuba'),
      ('Curacao'),
      ('Cyprus'),
      ('Czechia'),
      ('Democratic Republic of the Congo'),
      ('Denmark'),
      ('Dhekelia'),
      ('Djibouti'),
      ('Dominica'),
      ('Dominican Republic'),
      ('Ecuador'),
      ('Egypt'),
      ('El Salvador'),
      ('Equatorial Guinea'),
      ('Eritrea'),
      ('Estonia'),
      ('Eswatini'),
      ('Ethiopia'),
      ('Etorofu, Habomai, Kunashiri, and Shikotan Islands'),
      ('Europa Island'),
      ('Falkland Islands'),
      ('Faroe Islands'),
      ('Fiji'),
      ('Finland'),
      ('France'),
      ('French Guiana'),
      ('French Polynesia'),
      ('French Southern and Antarctic Lands'),
      ('Gabon'),
      ('Gambia'),
      ('Gaza Strip'),
      ('Georgia'),
      ('Germany'),
      ('Ghana'),
      ('Gibraltar'),
      ('Greece'),
      ('Greenland'),
      ('Grenada'),
      ('Guadeloupe'),
      ('Guam'),
      ('Guatemala'),
      ('Guernsey'),
      ('Guinea'),
      ('Guinea-Bissau'),
      ('Guyana'),
      ('Haiti'),
      ('Heard Island and McDonald Islands'),
      ('Holy See'),
      ('Honduras'),
      ('Hong Kong'),
      ('Howland Island'),
      ('Hungary'),
      ('Iceland'),
      ('India'),
      ('Indonesia'),
      ('Iran'),
      ('Iraq'),
      ('Ireland'),
      ('Isle of Man'),
      ('Israel'),
      ('Italy'),
      ('Ivory Coast'),
      ('Jamaica'),
      ('Jan Mayen'),
      ('Japan'),
      ('Jarvis Island'),
      ('Jersey'),
      ('Johnston Atoll'),
      ('Jordan'),
      ('Juan de Nova Island'),
      ('Kazakhstan'),
      ('Kenya'),
      ('Kingman Reef'),
      ('Kiribati'),
      ('Kosovo'),
      ('Kuwait'),
      ('Kyrgyzstan'),
      ('Lao'),
      ('Latvia'),
      ('Lebanon'),
      ('Lesotho'),
      ('Liberia'),
      ('Libya'),
      ('Liechtenstein'),
      ('Lithuania'),
      ('Luxembourg'),
      ('Macao'),
      ('Madagascar'),
      ('Malawi'),
      ('Malaysia'),
      ('Maldives'),
      ('Mali'),
      ('Malta'),
      ('Marshall Islands'),
      ('Martinique'),
      ('Mauritania'),
      ('Mauritius'),
      ('Mayotte'),
      ('Mexico'),
      ('Micronesia'),
      ('Midway Islands'),
      ('Moldova'),
      ('Monaco'),
      ('Mongolia'),
      ('Montenegro'),
      ('Montserrat'),
      ('Morocco'),
      ('Mozambique'),
      ('Myanmar'),
      ('Namibia'),
      ('Nauru'),
      ('Navassa Island'),
      ('Nepal'),
      ('Netherlands'),
      ('New Caledonia'),
      ('New Zealand'),
      ('Nicaragua'),
      ('Niger'),
      ('Nigeria'),
      ('Niue'),
      ('Norfolk Island'),
      ('North Korea'),
      ('North Macedonia'),
      ('Northern Mariana Islands'),
      ('Norway'),
      ('Oman'),
      ('Pakistan'),
      ('Palau'),
      ('Palestine'),
      ('Palmyra Atoll'),
      ('Panama'),
      ('Papua New Guinea'),
      ('Paracel Islands'),
      ('Paraguay'),
      ('Peru'),
      ('Philippines'),
      ('Pitcairn'),
      ('Poland'),
      ('Portugal'),
      ('Puerto Rico'),
      ('Qatar'),
      ('Reunion'),
      ('Romania'),
      ('Russia'),
      ('Rwanda'),
      ('Saint Barthelemy'),
      ('Saint Helena, Ascension and Tristan da Cunha'),
      ('Saint Kitts and Nevis'),
      ('Saint Lucia'),
      ('Saint Maarten (Dutch)'),
      ('Saint Martin (French)'),
      ('Saint Pierre and Miquelon'),
      ('Saint Vincent and the Grenadines'),
      ('Samoa'),
      ('San Marino'),
      ('Sao Tome and Principe'),
      ('Saudi Arabia'),
      ('Senegal'),
      ('Serbia'),
      ('Seychelles'),
      ('Sierra Leone'),
      ('Singapore'),
      ('Slovakia'),
      ('Slovenia'),
      ('Solomon Islands'),
      ('Somalia'),
      ('South Africa'),
      ('South Georgia and the South Sandwich Islands'),
      ('South Korea'),
      ('South Sudan'),
      ('Spain'),
      ('Spratly Islands'),
      ('Sri Lanka'),
      ('Sudan'),
      ('Suriname'),
      ('Svalbard and Jan Mayen'),
      ('Sweden'),
      ('Switzerland'),
      ('Syria'),
      ('Taiwan'),
      ('Tajikistan'),
      ('Tanzania, the United Republic of'),
      ('Thailand'),
      ('the British Virgin Islands'),
      ('Timor-Leste'),
      ('Togo'),
      ('Tokelau'),
      ('Tonga'),
      ('Trinidad and Tobago'),
      ('Tromelin Island'),
      ('Tunisia'),
      ('Turkey'),
      ('Turkmenistan'),
      ('Turks and Caicos Islands'),
      ('Tuvalu'),
      ('Uganda'),
      ('Ukraine'),
      ('United Arab Emirates'),
      ('United Kingdom of Great Britain and Northern Ireland'),
      ('United States Minor Outlying Islands'),
      ('United States of America'),
      ('Uruguay'),
      ('Uzbekistan'),
      ('Vanuatu'),
      ('Venezuela'),
      ('Vietnam'),
      ('Virgin Islands'),
      ('Wake Island'),
      ('Wallis and Futuna'),
      ('West Bank'),
      ('Western Sahara'),
      ('Yemen'),
      ('Zambia'),
      ('Zimbabwe')
  ) as countries(country_name);

  with ranked_regions as (
    select
      id,
      row_number() over (
        order by
          case when id = global_region_id then 0 else 1 end,
          sort_order asc,
          created_at asc,
          lower(btrim(name)) asc
      ) as next_sort_order
    from public.filter_regions
  )
  update public.filter_regions as regions
  set sort_order = ranked_regions.next_sort_order
  from ranked_regions
  where regions.id = ranked_regions.id;
end
$$;
