create temporary table canonical_filter_regions (
  region_key text primary key,
  preferred_id uuid not null,
  name text not null,
  description text not null,
  sort_order integer not null
) on commit drop;

create temporary table canonical_filter_region_countries (
  region_key text not null references canonical_filter_regions(region_key) on delete cascade,
  country_name text not null
) on commit drop;

create temporary table resolved_filter_regions (
  region_key text primary key,
  region_id uuid not null
) on commit drop;

insert into canonical_filter_regions (
  region_key,
  preferred_id,
  name,
  description,
  sort_order
)
values
  ('global', 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', 'Global', 'All countries', 1),
  ('africa-east-and-southern', '10000000-0000-4000-8000-000000000001', 'Africa, East and Southern', '', 2),
  ('africa-north-and-middle-east', '10000000-0000-4000-8000-000000000002', 'Africa, North and Middle East', '', 3),
  ('africa-west-and-central', '10000000-0000-4000-8000-000000000003', 'Africa, West and Central', '', 4),
  ('america-latin', '10000000-0000-4000-8000-000000000004', 'America, Latin', '', 5),
  ('america-north-and-caribbean', '10000000-0000-4000-8000-000000000005', 'America, North and Caribbean', '', 6),
  ('asia-central', '10000000-0000-4000-8000-000000000006', 'Asia, Central', '', 7),
  ('asia-northeast', '10000000-0000-4000-8000-000000000007', 'Asia, Northeast', '', 8),
  ('asia-south', '10000000-0000-4000-8000-000000000008', 'Asia, South', '', 9),
  ('asia-southeast', '10000000-0000-4000-8000-000000000009', 'Asia, Southeast', '', 10),
  ('australia-and-pacific', '10000000-0000-4000-8000-000000000010', 'Australia and Pacific', '', 11),
  ('europe-eastern-and-eurasia', '10000000-0000-4000-8000-000000000011', 'Europe, Eastern and Eurasia', '', 12),
  ('europe-western', '10000000-0000-4000-8000-000000000012', 'Europe, Western', '', 13);

insert into canonical_filter_region_countries (region_key, country_name)
values
  ('global', 'Afghanistan'),
  ('global', 'Akrotiri'),
  ('global', 'Aland Islands'),
  ('global', 'Albania'),
  ('global', 'Algeria'),
  ('global', 'American Samoa'),
  ('global', 'Andorra'),
  ('global', 'Angola'),
  ('global', 'Anguilla'),
  ('global', 'Antarctica'),
  ('global', 'Antigua and Barbuda'),
  ('global', 'Argentina'),
  ('global', 'Armenia'),
  ('global', 'Aruba'),
  ('global', 'Ashmore and Cartier Islands'),
  ('global', 'Australia'),
  ('global', 'Austria'),
  ('global', 'Azerbaijan'),
  ('global', 'Bahamas'),
  ('global', 'Bahrain'),
  ('global', 'Baker Island'),
  ('global', 'Bangladesh'),
  ('global', 'Barbados'),
  ('global', 'Bassas da India'),
  ('global', 'Belarus'),
  ('global', 'Belgium'),
  ('global', 'Belize'),
  ('global', 'Benin'),
  ('global', 'Bermuda'),
  ('global', 'Bhutan'),
  ('global', 'Bolivia'),
  ('global', 'Bonaire, Sint Eustatius and Saba'),
  ('global', 'Bosnia and Herzegovina'),
  ('global', 'Botswana'),
  ('global', 'Bouvet Island'),
  ('global', 'Brazil'),
  ('global', 'British Indian Ocean Territory'),
  ('global', 'Brunei Darussalam'),
  ('global', 'Bulgaria'),
  ('global', 'Burkina Faso'),
  ('global', 'Burundi'),
  ('global', 'Cabo Verde'),
  ('global', 'Cambodia'),
  ('global', 'Cameroon'),
  ('global', 'Canada'),
  ('global', 'Cayman Islands'),
  ('global', 'Central African Republic'),
  ('global', 'Chad'),
  ('global', 'Chile'),
  ('global', 'China'),
  ('global', 'Christmas Island'),
  ('global', 'Clipperton Island'),
  ('global', 'Cocos Islands'),
  ('global', 'Colombia'),
  ('global', 'Comoros'),
  ('global', 'Congo'),
  ('global', 'Cook Islands'),
  ('global', 'Costa Rica'),
  ('global', 'Croatia'),
  ('global', 'Cuba'),
  ('global', 'Curacao'),
  ('global', 'Cyprus'),
  ('global', 'Czechia'),
  ('global', 'Democratic Republic of the Congo'),
  ('global', 'Denmark'),
  ('global', 'Dhekelia'),
  ('global', 'Djibouti'),
  ('global', 'Dominica'),
  ('global', 'Dominican Republic'),
  ('global', 'Ecuador'),
  ('global', 'Egypt'),
  ('global', 'El Salvador'),
  ('global', 'Equatorial Guinea'),
  ('global', 'Eritrea'),
  ('global', 'Estonia'),
  ('global', 'Eswatini'),
  ('global', 'Ethiopia'),
  ('global', 'Etorofu, Habomai, Kunashiri, and Shikotan Islands'),
  ('global', 'Europa Island'),
  ('global', 'Falkland Islands'),
  ('global', 'Faroe Islands'),
  ('global', 'Fiji'),
  ('global', 'Finland'),
  ('global', 'France'),
  ('global', 'French Guiana'),
  ('global', 'French Polynesia'),
  ('global', 'French Southern and Antarctic Lands'),
  ('global', 'Gabon'),
  ('global', 'Gambia'),
  ('global', 'Gaza Strip'),
  ('global', 'Georgia'),
  ('global', 'Germany'),
  ('global', 'Ghana'),
  ('global', 'Gibraltar'),
  ('global', 'Greece'),
  ('global', 'Greenland'),
  ('global', 'Grenada'),
  ('global', 'Guadeloupe'),
  ('global', 'Guam'),
  ('global', 'Guatemala'),
  ('global', 'Guernsey'),
  ('global', 'Guinea'),
  ('global', 'Guinea-Bissau'),
  ('global', 'Guyana'),
  ('global', 'Haiti'),
  ('global', 'Heard Island and McDonald Islands'),
  ('global', 'Holy See'),
  ('global', 'Honduras'),
  ('global', 'Hong Kong'),
  ('global', 'Howland Island'),
  ('global', 'Hungary'),
  ('global', 'Iceland'),
  ('global', 'India'),
  ('global', 'Indonesia'),
  ('global', 'Iran'),
  ('global', 'Iraq'),
  ('global', 'Ireland'),
  ('global', 'Isle of Man'),
  ('global', 'Israel'),
  ('global', 'Italy'),
  ('global', 'Ivory Coast'),
  ('global', 'Jamaica'),
  ('global', 'Jan Mayen'),
  ('global', 'Japan'),
  ('global', 'Jarvis Island'),
  ('global', 'Jersey'),
  ('global', 'Johnston Atoll'),
  ('global', 'Jordan'),
  ('global', 'Juan de Nova Island'),
  ('global', 'Kazakhstan'),
  ('global', 'Kenya'),
  ('global', 'Kingman Reef'),
  ('global', 'Kiribati'),
  ('global', 'Kosovo'),
  ('global', 'Kuwait'),
  ('global', 'Kyrgyzstan'),
  ('global', 'Lao'),
  ('global', 'Latvia'),
  ('global', 'Lebanon'),
  ('global', 'Lesotho'),
  ('global', 'Liberia'),
  ('global', 'Libya'),
  ('global', 'Liechtenstein'),
  ('global', 'Lithuania'),
  ('global', 'Luxembourg'),
  ('global', 'Macao'),
  ('global', 'Madagascar'),
  ('global', 'Malawi'),
  ('global', 'Malaysia'),
  ('global', 'Maldives'),
  ('global', 'Mali'),
  ('global', 'Malta'),
  ('global', 'Marshall Islands'),
  ('global', 'Martinique'),
  ('global', 'Mauritania'),
  ('global', 'Mauritius'),
  ('global', 'Mayotte'),
  ('global', 'Mexico'),
  ('global', 'Micronesia'),
  ('global', 'Midway Islands'),
  ('global', 'Moldova'),
  ('global', 'Monaco'),
  ('global', 'Mongolia'),
  ('global', 'Montenegro'),
  ('global', 'Montserrat'),
  ('global', 'Morocco'),
  ('global', 'Mozambique'),
  ('global', 'Myanmar'),
  ('global', 'Namibia'),
  ('global', 'Nauru'),
  ('global', 'Navassa Island'),
  ('global', 'Nepal'),
  ('global', 'Netherlands'),
  ('global', 'New Caledonia'),
  ('global', 'New Zealand'),
  ('global', 'Nicaragua'),
  ('global', 'Niger'),
  ('global', 'Nigeria'),
  ('global', 'Niue'),
  ('global', 'Norfolk Island'),
  ('global', 'North Korea'),
  ('global', 'North Macedonia'),
  ('global', 'Northern Mariana Islands'),
  ('global', 'Norway'),
  ('global', 'Oman'),
  ('global', 'Pakistan'),
  ('global', 'Palau'),
  ('global', 'Palestine'),
  ('global', 'Palmyra Atoll'),
  ('global', 'Panama'),
  ('global', 'Papua New Guinea'),
  ('global', 'Paracel Islands'),
  ('global', 'Paraguay'),
  ('global', 'Peru'),
  ('global', 'Philippines'),
  ('global', 'Pitcairn'),
  ('global', 'Poland'),
  ('global', 'Portugal'),
  ('global', 'Puerto Rico'),
  ('global', 'Qatar'),
  ('global', 'Reunion'),
  ('global', 'Romania'),
  ('global', 'Russia'),
  ('global', 'Rwanda'),
  ('global', 'Saint Barthelemy'),
  ('global', 'Saint Helena, Ascension and Tristan da Cunha'),
  ('global', 'Saint Kitts and Nevis'),
  ('global', 'Saint Lucia'),
  ('global', 'Saint Maarten (Dutch)'),
  ('global', 'Saint Martin (French)'),
  ('global', 'Saint Pierre and Miquelon'),
  ('global', 'Saint Vincent and the Grenadines'),
  ('global', 'Samoa'),
  ('global', 'San Marino'),
  ('global', 'Sao Tome and Principe'),
  ('global', 'Saudi Arabia'),
  ('global', 'Senegal'),
  ('global', 'Serbia'),
  ('global', 'Seychelles'),
  ('global', 'Sierra Leone'),
  ('global', 'Singapore'),
  ('global', 'Slovakia'),
  ('global', 'Slovenia'),
  ('global', 'Solomon Islands'),
  ('global', 'Somalia'),
  ('global', 'South Africa'),
  ('global', 'South Georgia and the South Sandwich Islands'),
  ('global', 'South Korea'),
  ('global', 'South Sudan'),
  ('global', 'Spain'),
  ('global', 'Spratly Islands'),
  ('global', 'Sri Lanka'),
  ('global', 'Sudan'),
  ('global', 'Suriname'),
  ('global', 'Svalbard and Jan Mayen'),
  ('global', 'Sweden'),
  ('global', 'Switzerland'),
  ('global', 'Syria'),
  ('global', 'Taiwan'),
  ('global', 'Tajikistan'),
  ('global', 'Tanzania, the United Republic of'),
  ('global', 'Thailand'),
  ('global', 'the British Virgin Islands'),
  ('global', 'Timor-Leste'),
  ('global', 'Togo'),
  ('global', 'Tokelau'),
  ('global', 'Tonga'),
  ('global', 'Trinidad and Tobago'),
  ('global', 'Tromelin Island'),
  ('global', 'Tunisia'),
  ('global', 'Turkey'),
  ('global', 'Turkmenistan'),
  ('global', 'Turks and Caicos Islands'),
  ('global', 'Tuvalu'),
  ('global', 'Uganda'),
  ('global', 'Ukraine'),
  ('global', 'United Arab Emirates'),
  ('global', 'United Kingdom of Great Britain and Northern Ireland'),
  ('global', 'United States Minor Outlying Islands'),
  ('global', 'United States of America'),
  ('global', 'Uruguay'),
  ('global', 'Uzbekistan'),
  ('global', 'Vanuatu'),
  ('global', 'Venezuela'),
  ('global', 'Vietnam'),
  ('global', 'Virgin Islands'),
  ('global', 'Wake Island'),
  ('global', 'Wallis and Futuna'),
  ('global', 'West Bank'),
  ('global', 'Western Sahara'),
  ('global', 'Yemen'),
  ('global', 'Zambia'),
  ('global', 'Zimbabwe'),
  ('africa-east-and-southern', 'Angola'),
  ('africa-east-and-southern', 'Botswana'),
  ('africa-east-and-southern', 'Burundi'),
  ('africa-east-and-southern', 'Comoros'),
  ('africa-east-and-southern', 'Djibouti'),
  ('africa-east-and-southern', 'Eritrea'),
  ('africa-east-and-southern', 'Eswatini'),
  ('africa-east-and-southern', 'Ethiopia'),
  ('africa-east-and-southern', 'Kenya'),
  ('africa-east-and-southern', 'Lesotho'),
  ('africa-east-and-southern', 'Madagascar'),
  ('africa-east-and-southern', 'Malawi'),
  ('africa-east-and-southern', 'Mauritius'),
  ('africa-east-and-southern', 'Mayotte'),
  ('africa-east-and-southern', 'Mozambique'),
  ('africa-east-and-southern', 'Namibia'),
  ('africa-east-and-southern', 'Reunion'),
  ('africa-east-and-southern', 'Rwanda'),
  ('africa-east-and-southern', 'Saint Helena, Ascension and Tristan da Cunha'),
  ('africa-east-and-southern', 'Seychelles'),
  ('africa-east-and-southern', 'Somalia'),
  ('africa-east-and-southern', 'South Africa'),
  ('africa-east-and-southern', 'South Sudan'),
  ('africa-east-and-southern', 'Sudan'),
  ('africa-east-and-southern', 'Tanzania, the United Republic of'),
  ('africa-east-and-southern', 'Uganda'),
  ('africa-east-and-southern', 'Zambia'),
  ('africa-east-and-southern', 'Zimbabwe'),
  ('africa-north-and-middle-east', 'Algeria'),
  ('africa-north-and-middle-east', 'Bahrain'),
  ('africa-north-and-middle-east', 'Egypt'),
  ('africa-north-and-middle-east', 'Iraq'),
  ('africa-north-and-middle-east', 'Israel'),
  ('africa-north-and-middle-east', 'Jordan'),
  ('africa-north-and-middle-east', 'Kuwait'),
  ('africa-north-and-middle-east', 'Lebanon'),
  ('africa-north-and-middle-east', 'Libya'),
  ('africa-north-and-middle-east', 'Morocco'),
  ('africa-north-and-middle-east', 'Oman'),
  ('africa-north-and-middle-east', 'Qatar'),
  ('africa-north-and-middle-east', 'Saudi Arabia'),
  ('africa-north-and-middle-east', 'Syria'),
  ('africa-north-and-middle-east', 'Tunisia'),
  ('africa-north-and-middle-east', 'United Arab Emirates'),
  ('africa-north-and-middle-east', 'West Bank'),
  ('africa-north-and-middle-east', 'Gaza Strip'),
  ('africa-north-and-middle-east', 'Palestine'),
  ('africa-north-and-middle-east', 'Western Sahara'),
  ('africa-north-and-middle-east', 'Yemen'),
  ('africa-west-and-central', 'Benin'),
  ('africa-west-and-central', 'Burkina Faso'),
  ('africa-west-and-central', 'Cameroon'),
  ('africa-west-and-central', 'Cabo Verde'),
  ('africa-west-and-central', 'Central African Republic'),
  ('africa-west-and-central', 'Chad'),
  ('africa-west-and-central', 'Democratic Republic of the Congo'),
  ('africa-west-and-central', 'Congo'),
  ('africa-west-and-central', 'Ivory Coast'),
  ('africa-west-and-central', 'Equatorial Guinea'),
  ('africa-west-and-central', 'Gabon'),
  ('africa-west-and-central', 'Gambia'),
  ('africa-west-and-central', 'Ghana'),
  ('africa-west-and-central', 'Guinea'),
  ('africa-west-and-central', 'Guinea-Bissau'),
  ('africa-west-and-central', 'Liberia'),
  ('africa-west-and-central', 'Mali'),
  ('africa-west-and-central', 'Mauritania'),
  ('africa-west-and-central', 'Niger'),
  ('africa-west-and-central', 'Nigeria'),
  ('africa-west-and-central', 'Sao Tome and Principe'),
  ('africa-west-and-central', 'Senegal'),
  ('africa-west-and-central', 'Sierra Leone'),
  ('africa-west-and-central', 'Togo'),
  ('america-latin', 'Argentina'),
  ('america-latin', 'Belize'),
  ('america-latin', 'Bolivia'),
  ('america-latin', 'Brazil'),
  ('america-latin', 'Chile'),
  ('america-latin', 'Colombia'),
  ('america-latin', 'Costa Rica'),
  ('america-latin', 'Ecuador'),
  ('america-latin', 'El Salvador'),
  ('america-latin', 'Falkland Islands'),
  ('america-latin', 'French Guiana'),
  ('america-latin', 'Guatemala'),
  ('america-latin', 'Guyana'),
  ('america-latin', 'Honduras'),
  ('america-latin', 'Mexico'),
  ('america-latin', 'Nicaragua'),
  ('america-latin', 'Panama'),
  ('america-latin', 'Paraguay'),
  ('america-latin', 'Peru'),
  ('america-latin', 'Suriname'),
  ('america-latin', 'Uruguay'),
  ('america-latin', 'Venezuela'),
  ('america-north-and-caribbean', 'Anguilla'),
  ('america-north-and-caribbean', 'Antigua and Barbuda'),
  ('america-north-and-caribbean', 'Aruba'),
  ('america-north-and-caribbean', 'Bahamas'),
  ('america-north-and-caribbean', 'Barbados'),
  ('america-north-and-caribbean', 'Bermuda'),
  ('america-north-and-caribbean', 'the British Virgin Islands'),
  ('america-north-and-caribbean', 'Canada'),
  ('america-north-and-caribbean', 'Cayman Islands'),
  ('america-north-and-caribbean', 'Cuba'),
  ('america-north-and-caribbean', 'Curacao'),
  ('america-north-and-caribbean', 'Dominica'),
  ('america-north-and-caribbean', 'Dominican Republic'),
  ('america-north-and-caribbean', 'Greenland'),
  ('america-north-and-caribbean', 'Grenada'),
  ('america-north-and-caribbean', 'Guadeloupe'),
  ('america-north-and-caribbean', 'Haiti'),
  ('america-north-and-caribbean', 'Jamaica'),
  ('america-north-and-caribbean', 'Martinique'),
  ('america-north-and-caribbean', 'Montserrat'),
  ('america-north-and-caribbean', 'Puerto Rico'),
  ('america-north-and-caribbean', 'Saint Kitts and Nevis'),
  ('america-north-and-caribbean', 'Saint Lucia'),
  ('america-north-and-caribbean', 'Saint Pierre and Miquelon'),
  ('america-north-and-caribbean', 'Saint Maarten (Dutch)'),
  ('america-north-and-caribbean', 'Saint Vincent and the Grenadines'),
  ('america-north-and-caribbean', 'Trinidad and Tobago'),
  ('america-north-and-caribbean', 'Turks and Caicos Islands'),
  ('america-north-and-caribbean', 'United States of America'),
  ('america-north-and-caribbean', 'Virgin Islands'),
  ('asia-central', 'Afghanistan'),
  ('asia-central', 'Armenia'),
  ('asia-central', 'Azerbaijan'),
  ('asia-central', 'Iran'),
  ('asia-central', 'Kazakhstan'),
  ('asia-central', 'Kyrgyzstan'),
  ('asia-central', 'Tajikistan'),
  ('asia-central', 'Turkey'),
  ('asia-central', 'Turkmenistan'),
  ('asia-central', 'Uzbekistan'),
  ('asia-northeast', 'China'),
  ('asia-northeast', 'Hong Kong'),
  ('asia-northeast', 'Macao'),
  ('asia-northeast', 'Japan'),
  ('asia-northeast', 'North Korea'),
  ('asia-northeast', 'South Korea'),
  ('asia-northeast', 'Mongolia'),
  ('asia-northeast', 'Taiwan'),
  ('asia-south', 'Bangladesh'),
  ('asia-south', 'Bhutan'),
  ('asia-south', 'British Indian Ocean Territory'),
  ('asia-south', 'India'),
  ('asia-south', 'Maldives'),
  ('asia-south', 'Nepal'),
  ('asia-south', 'Pakistan'),
  ('asia-south', 'Sri Lanka'),
  ('asia-southeast', 'Brunei Darussalam'),
  ('asia-southeast', 'Cambodia'),
  ('asia-southeast', 'Indonesia'),
  ('asia-southeast', 'Lao'),
  ('asia-southeast', 'Malaysia'),
  ('asia-southeast', 'Myanmar'),
  ('asia-southeast', 'Philippines'),
  ('asia-southeast', 'Singapore'),
  ('asia-southeast', 'Thailand'),
  ('asia-southeast', 'Timor-Leste'),
  ('asia-southeast', 'Vietnam'),
  ('australia-and-pacific', 'American Samoa'),
  ('australia-and-pacific', 'Australia'),
  ('australia-and-pacific', 'Christmas Island'),
  ('australia-and-pacific', 'Cocos Islands'),
  ('australia-and-pacific', 'Cook Islands'),
  ('australia-and-pacific', 'Fiji'),
  ('australia-and-pacific', 'French Polynesia'),
  ('australia-and-pacific', 'Guam'),
  ('australia-and-pacific', 'Kiribati'),
  ('australia-and-pacific', 'Marshall Islands'),
  ('australia-and-pacific', 'Micronesia'),
  ('australia-and-pacific', 'Nauru'),
  ('australia-and-pacific', 'New Caledonia'),
  ('australia-and-pacific', 'New Zealand'),
  ('australia-and-pacific', 'Niue'),
  ('australia-and-pacific', 'Norfolk Island'),
  ('australia-and-pacific', 'Northern Mariana Islands'),
  ('australia-and-pacific', 'Palau'),
  ('australia-and-pacific', 'Papua New Guinea'),
  ('australia-and-pacific', 'Pitcairn'),
  ('australia-and-pacific', 'Samoa'),
  ('australia-and-pacific', 'Solomon Islands'),
  ('australia-and-pacific', 'Tokelau'),
  ('australia-and-pacific', 'Tonga'),
  ('australia-and-pacific', 'Tuvalu'),
  ('australia-and-pacific', 'Vanuatu'),
  ('australia-and-pacific', 'Wallis and Futuna'),
  ('europe-eastern-and-eurasia', 'Albania'),
  ('europe-eastern-and-eurasia', 'Belarus'),
  ('europe-eastern-and-eurasia', 'Bosnia and Herzegovina'),
  ('europe-eastern-and-eurasia', 'Bulgaria'),
  ('europe-eastern-and-eurasia', 'Croatia'),
  ('europe-eastern-and-eurasia', 'Czechia'),
  ('europe-eastern-and-eurasia', 'Estonia'),
  ('europe-eastern-and-eurasia', 'Georgia'),
  ('europe-eastern-and-eurasia', 'Greece'),
  ('europe-eastern-and-eurasia', 'Hungary'),
  ('europe-eastern-and-eurasia', 'Kosovo'),
  ('europe-eastern-and-eurasia', 'Latvia'),
  ('europe-eastern-and-eurasia', 'Lithuania'),
  ('europe-eastern-and-eurasia', 'Moldova'),
  ('europe-eastern-and-eurasia', 'Montenegro'),
  ('europe-eastern-and-eurasia', 'North Macedonia'),
  ('europe-eastern-and-eurasia', 'Poland'),
  ('europe-eastern-and-eurasia', 'Romania'),
  ('europe-eastern-and-eurasia', 'Russia'),
  ('europe-eastern-and-eurasia', 'Serbia'),
  ('europe-eastern-and-eurasia', 'Slovakia'),
  ('europe-eastern-and-eurasia', 'Slovenia'),
  ('europe-eastern-and-eurasia', 'Ukraine'),
  ('europe-western', 'Andorra'),
  ('europe-western', 'Austria'),
  ('europe-western', 'Belgium'),
  ('europe-western', 'Cyprus'),
  ('europe-western', 'Denmark'),
  ('europe-western', 'Faroe Islands'),
  ('europe-western', 'Finland'),
  ('europe-western', 'France'),
  ('europe-western', 'Germany'),
  ('europe-western', 'Gibraltar'),
  ('europe-western', 'Iceland'),
  ('europe-western', 'Ireland'),
  ('europe-western', 'Isle of Man'),
  ('europe-western', 'Italy'),
  ('europe-western', 'Liechtenstein'),
  ('europe-western', 'Luxembourg'),
  ('europe-western', 'Malta'),
  ('europe-western', 'Monaco'),
  ('europe-western', 'Netherlands'),
  ('europe-western', 'Norway'),
  ('europe-western', 'Portugal'),
  ('europe-western', 'San Marino'),
  ('europe-western', 'Spain'),
  ('europe-western', 'Svalbard and Jan Mayen'),
  ('europe-western', 'Sweden'),
  ('europe-western', 'Switzerland'),
  ('europe-western', 'United Kingdom of Great Britain and Northern Ireland'),
  ('europe-western', 'Holy See');

do $$
declare
  canonical_region record;
  resolved_region_id uuid;
begin
  for canonical_region in
    select *
    from canonical_filter_regions
    order by sort_order asc
  loop
    resolved_region_id := null;

    if canonical_region.region_key = 'global' then
      select regions.id
      into resolved_region_id
      from public.filter_regions as regions
      where lower(btrim(regions.name)) in ('global', 'globe')
      order by
        case when lower(btrim(regions.name)) = 'global' then 0 else 1 end,
        regions.created_at asc
      limit 1;
    elsif canonical_region.region_key = 'asia-south' then
      select regions.id
      into resolved_region_id
      from public.filter_regions as regions
      where lower(btrim(regions.name)) in ('asia, south', 'south asia')
      order by
        case when lower(btrim(regions.name)) = 'asia, south' then 0 else 1 end,
        regions.created_at asc
      limit 1;
    elsif canonical_region.region_key = 'asia-southeast' then
      select regions.id
      into resolved_region_id
      from public.filter_regions as regions
      where lower(btrim(regions.name)) in ('asia, southeast', 'south east asia')
      order by
        case when lower(btrim(regions.name)) = 'asia, southeast' then 0 else 1 end,
        regions.created_at asc
      limit 1;
    else
      select regions.id
      into resolved_region_id
      from public.filter_regions as regions
      where lower(btrim(regions.name)) = lower(canonical_region.name)
      order by regions.created_at asc
      limit 1;
    end if;

    if resolved_region_id is null then
      resolved_region_id := canonical_region.preferred_id;

      insert into public.filter_regions (
        id,
        name,
        description,
        sort_order
      )
      values (
        resolved_region_id,
        canonical_region.name,
        canonical_region.description,
        canonical_region.sort_order
      )
      on conflict (id) do update
      set
        name = excluded.name,
        description = excluded.description,
        sort_order = excluded.sort_order,
        updated_at = now();
    else
      update public.filter_regions
      set
        name = canonical_region.name,
        description = canonical_region.description,
        sort_order = canonical_region.sort_order,
        updated_at = now()
      where id = resolved_region_id;
    end if;

    insert into resolved_filter_regions (region_key, region_id)
    values (canonical_region.region_key, resolved_region_id)
    on conflict (region_key) do update
    set region_id = excluded.region_id;
  end loop;
end $$;

delete from public.filter_regions
where id not in (
  select region_id
  from resolved_filter_regions
);

delete from public.filter_region_countries;

insert into public.filter_region_countries (
  region_id,
  country_name
)
select
  resolved.region_id,
  countries.country_name
from canonical_filter_region_countries as countries
join resolved_filter_regions as resolved
  on resolved.region_key = countries.region_key
order by resolved.region_id, countries.country_name;

drop policy if exists "dataset admin can insert filter regions"
  on public.filter_regions;
drop policy if exists "dataset admin can update filter regions"
  on public.filter_regions;
drop policy if exists "dataset admin can delete filter regions"
  on public.filter_regions;

drop policy if exists "dataset admin can insert filter region countries"
  on public.filter_region_countries;
drop policy if exists "dataset admin can update filter region countries"
  on public.filter_region_countries;
drop policy if exists "dataset admin can delete filter region countries"
  on public.filter_region_countries;
