name: Release Health

on:
  push:
    branches:
      - main

concurrency:
  group: release-health-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  deployments: read

jobs:
  release-health:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: ./.github/actions/setup-pnpm-node

      - run: pnpm install --frozen-lockfile
      - run: pnpm run release:health -- --sha "${{ github.sha }}"
